src/timetable/urls.py
from django.urls import path

from .views import homepage, createPlanning

urlpatterns = [
    path('', homepage, name="timetable-homepage"),
    path('createPlanning', createPlanning, name='createPlanning')
]

src/timetable_management/urls.py
from django.contrib import admin
from django.urls import path, include

from timetable_management.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("timetable.urls")),
]

src/timetable/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Dept(models.Model):
    nom_dpt = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Département"
    def __str__(self):
        return self.nom_dpt

    def get_absolute_url(self):
        return reverse("timetable-homepage")



class Filiere(models.Model):
    nom_filiere = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    class Meta:
        verbose_name = "Filière"
    def __str__(self):
        return self.nom_filiere

    def get_absolute_url(self):
        return reverse("timetable-homepage")

class Promo(models.Model):
    nom_promo = models.CharField(max_length=20)

    class Meta:
        verbose_name = "Promotion"
    def __str__(self):
        return self.nom_promo

    def get_absolute_url(self):
        return reverse("timetable-homepage")


class Cours(models.Model):
    identifiant = models.CharField(max_length=50)
    libelle = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Cour"
    def __str__(self):
        return self.libelle

    def get_absolute_url(self):
        return reverse("timetable-homepage")

class Salle(models.Model):
    nom = models.CharField(max_length=20)
    description = models.CharField(max_length=20)

    class Meta:
        verbose_name = "Salle"
    def __str__(self):
        return f"{self.nom} {self.description}"

    def get_absolute_url(self):
        return reverse("timetable-homepage")


class Prof(models.Model):
    nom = models.CharField(max_length=30)


    class Meta:
        verbose_name = "Professeur"
    def __str__(self):
        return self.nom

    def get_absolute_url(self):
        return reverse("timetable-homepage")

class Creneau(models.Model):
    filiere = models.ForeignKey(Filiere, on_delete=models.CASCADE, default=None)
    cours = models.ForeignKey(Cours, on_delete=models.SET_NULL, null=True)
    prof = models.ForeignKey(Prof, on_delete=models.SET_NULL, null=True)
    salle = models.ForeignKey(Salle, on_delete=models.SET_NULL, null=True)
    date_debut = models.DateTimeField()
    date_fin = models.DateTimeField()

src/timetable/forms.py
from django import forms
from timetable.models import Creneau


class CreatePlanningForm(forms.ModelForm):
    class Meta:
        model = Creneau
        exclude = ['date_debut', 'date_fin']

    date_de_debut = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    date_de_fin = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

src/timetable/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from timetable.forms import CreatePlanningForm
from timetable.models import Creneau


# Create your views here.
def homepage(request):
    creneaux = Creneau.objects.all()
    return render(request, 'timetable/index.html', context={'creneaux': creneaux})

def createPlanning(request):
    if request.method == 'POST':
        form = CreatePlanningForm(request.POST)
        if form.is_valid():
            create_planning = form.save(commit=False)
            create_planning.date_debut = form.cleaned_data['date_de_debut']
            create_planning.date_fin = form.cleaned_data['date_de_fin']
            create_planning.save()
        return HttpResponseRedirect(request.path)
            # créer une nouvelle « emplois » et la sauvegarder dans la db

            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection

    else:
        form = CreatePlanningForm()

    return render(request, 'timetable/createPlanning.html', {"form": form})

src/timetable_management/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'timetableManagement/index.html')

src/timetable/templates/timetable/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %} {% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">


<!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  </head>

<body>

{% block header %} {% endblock header %}

  <main id="main">

    

    <section class="inner-page">
      <div class="container">
        {% block content %}  {% endblock content %}
      </div>
    </section>

  </main><!-- End #main -->

  <div id="preloader"></div>
  <a style="color: black;" href="#" class="back-to-top d-flex align-items-center justify-content-center"> haut<i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
<script>
  $(function () {
    $("#id_date_de_debut").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });

  $(function () {
    $("#id_date_de_fin").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
</script>
</body>

</html>

src/timetable/templates/timetable/createPlanning.html
{% extends 'timetable/base.html' %}
{% load widget_tweaks %}
{% block tilte %} <h1>Ajouter Créneau <h1> {% endblock tilte %}


{% block content %}


<div class = "container" >
  <form action="" method="post" class="row g-3 w-50 p-3 " > <!--  l' attribut de Form "novalidate" permet de desactiver la validation coté client -->
    <fieldset>
      <legend> Ajouter un créneau </legend>
      {% csrf_token %}




      <div class="mb-5">
        <label for="filiere" class="form-label">Filière</label>
        {% render_field form.filiere class+='form-control' id="filiere"%}
      </div>
      <div class="mb-5">
        <label for="salle" class="form-label">Salle</label>
        {% render_field form.salle class+='form-control' id="salle"%}
      </div>
      <div class="mb-5">
        <label for="cours" class="form-label">Cours</label>
        {% render_field form.cours class+='form-control' id="cours"%}
      </div>
      <div class="mb-5">
        <label for="prof" class="form-label">Enseignant</label>
        {% render_field form.prof class+='form-control' id="prof"%}
      </div>
      <div class="mb-5">
        <label for="date_de_debut" class="form-label">Date De Debut</label>
        {% render_field form.date_de_debut class+='form-control' %}
      </div>

       <div class="mb-5">
        <label for="date_de_fin" class="form-label">Date De Fin</label>
        {% render_field form.date_de_fin class+='form-control' %}
      </div>

      <div class="form-group">
        <button class="btn btn-primary" type="submit">Valider</button>
      </div>
    </fieldset>
  </form>

</div>


{% endblock %}

src/timetable/templates/timetable/filterPlanning.html
{% extends 'timetable/base.html' %}
{% load widget_tweaks %}
{% block tilte %} <h1>Les créneaux filtres <h1> {% endblock tilte %}



    {% block header %}
    <div class="container mt-5">
      <h2 class="text-center alert text-white bg-primary"><a class="text-white" href="{% url 'timetable-homepage' %}">  GESTION DES EMPLOIS DU
        TEMPS</a> </h2>

    </div>

    {% endblock header %}

  {% block content %}
    <div class="container mt-1">

      <form method="GET" name="myform" action="{% url 'filterPlanning' %}" method="GET">

        <div class="row g-3">

          <!-- Choix de la filiere -->
          <div class="col-sm-4">
            <label for="filiere" class="form-label">FILIERE</label>
            <select class="form-control" name="filiere">
              <option value="none" selected>&#x3008;aucun&#x3009;</option>
              {% for creneau in creneaux %}
                 <option>{{creneau.filiere}}</option>
                {%endfor%}

            </select>
          </div>
          <br>
          <!-- Choix date et heure minimum -->
          <div class="col-sm-1">
            <label for="datemin" class="form-label">Date min</label>
            <input type="date" class="form-control" name="datemin">
          </div>
          <div class="col-sm-1">
            <label for="heuremin" class="form-label">Heure min</label>
            <input type="time" class="form-control" name="heuremin">
          </div>

          <!-- Choix date et heure maximum -->
          <div class="col-sm-1">
            <label for="datemax" class="form-label">Date max</label>
            <input type="date" class="form-control" name="datemax">
          </div>
          <div class="col-sm-1">
            <label for="heuremax" class="form-label">Heure max</label>
            <input type="time" class="form-control" name="heuremax">

          </div>
          <div class="col-sm-1 mt-5">
            <input type="submit" class="btn btn-primary" name="filtrer" value="Filtrer">
          </div>

        </div>
        <br>

        <div class="container mt-5">
          <h6 class="text-center alert text-white bg-primary">LISTE DES
            CRENEAUX</h6>
          <table class="table table-info table-hover">

            <thead>
              <tr>

                <th scope="col">num</th>
                <th scope="col">début</th>
                <th scope="col">fin</th>
                <th scope="col">cours</th>
                <th scope="col">salle</th>
                <th scope="col">prof</th>

              </tr>
            </thead>
            <tbody>





             {% for creneau in creneaux%}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{creneau.date_debut}}</td>
                <td>{{creneau.date_fin}}</td>
                <td>{{creneau.cours}}</a></td>
                <td>{{creneau.salle}}</td>
                <td>{{creneau.prof}}</td>
              </tr>
             {% endfor %}

              </tbody>
        </div>




        </tbody>

        </table>
          <p>

        <button type="button" class="btn btn-primary"><a class="text-light" href="{% url 'createPlanning' %}">Créer un nouveau créneau</a></button>
    </p>
    </div>


    {% endblock content %}

src/timetable/templates/timetable/index.html
{% extends 'timetable/base.html' %}

{% block tilte %} <h1>Les créneaux disponibles <h1> {% endblock tilte %}


    
    {% block header %} 
    <div class="container mt-5">
      <h2 class="text-center alert text-white bg-primary">GESTION DES EMPLOIS DU
        TEMPS</h2>

    </div>

    {% endblock header %}

    {% block content %}
    <div class="container mt-1">
      <form name="myform" method="GET" onsubmit="return
        verifier()">
        <div class="row g-3">

          <!-- Choix du cours -->
          <div class="col-sm-4">
            <label for="cours" class="form-label">FILIERE</label>
            <select class="form-control" name="cours">
              <option value="none" selected>&#x3008;aucun&#x3009;</option>
              {% for creneau in creneaux %}
                 <option>&#x3008;{{creneau.filiere}} &#x3009;</option>
                {%endfor%}

            </select>
          </div>
          <br>
          <!-- Choix date et heure minimum -->
          <div class="col-sm-1">
            <label for="datemin" class="form-label">Date min</label>
            <input type="date" class="form-control" name="datemin">
          </div>
          <div class="col-sm-1">
            <label for="heuremin" class="form-label">Heure min</label>
            <input type="time" class="form-control" name="heuremin">
          </div>

          <!-- Choix date et heure maximum -->
          <div class="col-sm-1">
            <label for="datemax" class="form-label">Date max</label>
            <input type="date" class="form-control" name="datemax">
          </div>
          <div class="col-sm-1">
            <label for="heuremax" class="form-label">Heure max</label>
            <input type="time" class="form-control" name="heuremax">

          </div>
          <div class="col-sm-1 mt-5">
            <input type="submit" class="btn btn-primary" name="go" value="Rafraîchir">
          </div>

        </div>
        <br>

        <div class="container mt-5">
          <h6 class="text-center alert text-white bg-primary">LISTE DES
            CRENEAUX</h6>
          <table class="table table-info table-hover">

            <thead>
              <tr>
                
                <th scope="col">num</th>
                <th scope="col">début</th>
                <th scope="col">fin</th>
                <th scope="col">cours</th>
                <th scope="col">salle</th>
                <th scope="col">prof</th>

              </tr>
            </thead>
            <tbody>


              

              
             {% for creneau in creneaux%}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{creneau.date_debut}}</td>
                <td>{{creneau.date_fin}}</td>
                <td>{{creneau.cours}}</a></td>
                <td>{{creneau.salle}}</td>
                <td>{{creneau.prof}}</td>
              </tr>
             {% endfor %}

              </tbody>
        </div>




        </tbody>

        </table>
    </div>
    <p>
      <a href="{% url 'createPlanning' %}">Créer un nouveau créneau</a>
    </p>

    {% endblock content %}

src/timetable_management/templates/timetableManagement/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Page d'accueil </title>
</head>
<body>
    Orci commodo semper cursus graeci fabellas. Facilisis viverra delectus risus facilisis disputationi non iudicabit expetenda. Vitae discere iisque tibique sollicitudin elit metus vix intellegebat nostrum. Blandit scripta blandit vestibulum populo possit dolores. Condimentum duo neque adhuc euripidis est pretium principes tractatos.
</body>
</html>